---
- name: Déployer une application Next.js sur EC2 avec Ansible
  hosts: webserver
  become: true

  vars:
    repo_url: "https://github.com/Omargazzah02/tasks-project.git"
    app_path: "/home/ubuntu/tasks-project"
 
    pm2_app_name: "next-app"

  tasks:

    - name: Mettre à jour les paquets
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installer Node.js et npm
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs



    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer Nginx
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Installer PM2 globalement
      npm:
        name: pm2
        global: yes

  

    - name: Cloner ou mettre à jour le dépôt GitHub
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: main
        update: yes
        force: yes


    - name: Installer les dépendances avec npm
      command: npm install
      args:
        chdir: "{{ app_path }}"



    
    - name: Test integrations
      command: npm test
      args:
        chdir: "{{ app_path }}"



    - name: Build le projet Next.js
      command: npm run build
      args:
        chdir: "{{ app_path }}"

    - name: Vérifier si l'application est déjà en cours d'exécution avec PM2
      command: pm2 list
      register: pm2_status
      changed_when: false


    - name: Démarrer l'application avec PM2 si elle n'est pas en cours d'exécution
      command: pm2 start npm --name "{{ pm2_app_name }}" -- run start -- --port 3000
      args:
        chdir: "{{ app_path }}"
      when: "pm2_app_name not in pm2_status.stdout"

    - name: Redémarrer l'application avec PM2 si elle est en cours d'exécution
      command: pm2 restart "{{ pm2_app_name }}"
      when: "pm2_app_name in pm2_status.stdout"

    





  handlers:
    - name: Redémarrer Nginx
      systemd:
        name: nginx
        state: restarted






